export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST'
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS'
export const CREATE_CHANNEL_FAILURE = 'CREATE_CHANNEL_FAILURE'

export const LIST_CHANNEL_REQUEST = 'LIST_CHANNEL_REQUEST'
export const LIST_CHANNEL_SUCCESS = 'LIST_CHANNEL_SUCCESS'
export const LIST_CHANNEL_FAILURE = 'LIST_CHANNEL_FAILURE'

export const JOIN_CHANNEL_REQUEST = 'JOIN_CHANNEL_REQUEST'
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS'
export const JOIN_CHANNEL_FAILURE = 'JOIN_CHANNEL_FAILURE'

export const DETAILS_CHANNEL_REQUEST = 'DETAILS_CHANNEL_REQUEST'
export const DETAILS_CHANNEL_SUCCESS = 'DETAILS_CHANNEL_SUCCESS'
export const DETAILS_CHANNEL_FAILURE = 'DETAILS_CHANNEL_FAILURE'

export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAILURE = 'MESSAGE_SEND_FAILURE'
export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAILURE = 'MESSAGE_LIST_FAILURE'