export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAILURE = 'MESSAGE_SEND_FAILURE'

// export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
// export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
// export const PRODUCT_UPDATE_FAILURE = 'PRODUCT_UPDATE_FAILURE'

export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAILURE = 'MESSAGE_LIST_FAILURE'

// export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
// export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
// export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'

// export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
// export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
// export const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE'